version: '2'
services:
    rpt-app:
        image: rpt
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:postgresql://rpt-postgresql:5432/rpt
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    rpt-postgresql:
        extends:
            file: postgresql.yml
            service: rpt-postgresql
